module.exports = {
    ra: {
        action: {
          add_filter:'Tambahkan filter',
          add: 'Tambahkan',
          back: 'Kembali',
          bulk_actions: '%{smart_count} terpilih',
          cancel: 'Batal',
          clear_input_value: 'Kosongkan input',
          clone:'Duplikat',
          confirm: 'Konfirmasi',
          create: 'Buat',
            delete: 'Hapus',
            edit: 'Ubah',
            export: 'Ekspor',
            list: 'Daftar',
            refresh: 'Perbaharui',
            remove_filter: 'Hapus filter',
            remove: 'Hapus',
            save: 'Simpan',
            search: 'Mencari',
            show: 'Tampilkan',
            sort: 'Pengurutan',
            undo: 'Batalkan',
            expand: 'Memperbesar',
            close: 'Tutup',
        },
        boolean: {
            true: 'Ya',
            false: 'Tidak',
        },
        page: {
          create: 'Buat %{name}',
          dashboard: 'Dasbor',
          edit: '%{name} #%{id}',
          error:'Ada yang salah',
          list: '%{name}',
          loading: 'Pemuatan',
          not_found: 'Tidak ditemukan',
          show: '%{name} #%{id}',
        },
        input: {
            file: {
                upload_several:'Letakan beberapa file untuk diunggah, atau klik untuk memilihnya.',
                upload_single: 'Letakan file yang akan diunggah, atau klik untuk memilihnya.',
            },
            image: {
                upload_several: 'Letakan beberapa gambar untuk diunggah, atau klik untuk memilihnya.',
                upload_single: 'Letakan gambar untuk diunggah, atau klik untuk memilihnya.',    
            },
            references: {
                all_missing: 'Tidak dapat menemukan data referensi.',
                many_missing:'Setidaknya satu referensi terkait tidak lagi tersedia.',
                single_missing:'Referensi terkait tidak lagi tersedia.',
            },
        },
        message: {
          about: 'Tentang',
          are_you_sure: 'Apakah anda yakin?',
          bulk_delete_content:'Anda yakin ingin menghapus %{name}? |||| Anda yakin ingin menghapus %{smart_count} items ini?',
          bulk_delete_title:'Hapus %{name} |||| Hapus %{smart_count} %{name} items',
          delete_content: 'Anda yakin ingin menghapus item ini?',
          delete_title: 'Hapus %{name} #%{id}',
          details:'Detail',
          error:'Terjadi kesalahan pada klien dan permintaan Anda tidak dapat diselesaikan.',
          invalid_form: 'Formulir tidak valid, ada kesalahan. Silakan periksa kembali',
          loading: 'Halaman ini sedang memuat, silahkan tunggu sebentar',
          no: 'Tidak',
          not_found:'Entah Anda mengetikkan URL yang salah, atau Anda memiliki link yang salah.',
          yes: 'Ya',
        },
        navigation: {
            no_results: 'Tidak ada hasil yang ditemukan',
            no_more_results:'Halaman %{page} tidak ada. Coba halaman sebelumnya.',
            page_out_of_boundaries: 'Halaman %{page} tidak ada',
            page_out_from_end: 'Halaman terakhir',
            page_out_from_begin: 'Halaman harus lebih besar dari pertama',
            page_range_info: '%{offsetBegin}-%{offsetEnd} dari %{total}',
            page_rows_per_page: 'Baris per halaman:',
            next: 'Berikutnya',
            prev: 'Sebelumnya',
        },
        auth: {
          user_menu: 'Profil',
          username: 'Nama pengguna',
          password: 'Kata sandi',
          sign_in: 'Masuk',
          sign_in_error: 'Otentikasi gagal, coba lagi',
          logout: 'Keluar',
        },
        notification: {
          updated: 'Elemen telah diperbaharui |||| %{smart_count} elemen telah diperbaharui',
          created: 'Elemen telah dibuat',
          deleted: 'Elemen telah dihapus |||| %{smart_count} elemen telah dihapus',
          bad_item: 'Elemen salah',
          item_doesnt_exist: 'Elemen tidak ada',
          http_error: 'Kesalahan komunikasi peladen',
          data_provider_error:'kesalahan pada dataProvider. Periksa konsol untuk detailnya.',
          canceled: 'Telah dibatalkan',
          logged_out: 'Sesi Anda telah berakhir, harap sambungkan kembali.',
        },
        validation: {
            required: 'Wajib',
            minLength: 'Minimal %{min} karakter',
            maxLength: 'Maksimal %{max} karakter atau kurang',
            minValue: 'Minimal %{min}',
            maxValue: 'Maksimal %{max} atau kurang',
            number: 'Harus Angka',
            email: 'Harus alamat email yang valid',
            oneOf: 'Harus salah satu dari : %{options}',
            regex: 'Harus sesuai dengan format tertentu (regexp): %{pattern}',
        },
    },
};
